DS-2925 Fix Critical vulnerability
LoyaltyNZ/alchemy-flux pull request #17
Opened 2023-07-12 19:09 UTC by ildomar-grings

## Overview

[DS-2925](https://loyaltynz.atlassian.net/browse/DS-2925)

## What is the change?
- WIP  
  
## How was this change made?

## How do I use/reproduce this change?

## Notes

2023-07-12 21:35 UTC, nickpiercy95 requested changes

2023-07-12 21:35 UTC, nickpiercy95 commented on .travis.yml
> +  - bundle exec bundle-audit check
Nice 💯

2023-07-12 21:35 UTC, nickpiercy95 commented on CHANGELOG.md
> +## v1.3.1
I think this should be a minor version bump, since we're we're updating Rack from 2.0 to 2.2

```suggestion
## v1.4.0
```

2023-07-13 03:28 UTC, ildomar-grings commented on CHANGELOG.md
> +## v1.3.1
Actually, based on the fact the application itself doesn't change, there are no new feature to consider on the counting. 

That is why I consider this update minor.

2023-07-18 00:08 UTC, nickpiercy95 commented on CHANGELOG.md
> +## v1.3.1
@ildomar-grings fair enough

2023-07-18 00:08 UTC, nickpiercy95 approved these changes

2023-07-18 02:25 UTC, pond commented on CHANGELOG.md
> +- Critical vulnerabilities update [DS-2925](https://loyaltynz.atlassian.net/browse/DS-2925)
This reference and this link are both meaningless to anyone outside of LNZL. Recommend copying details into a GitHub issue within this repo & referencing that instead.

2023-07-18 02:25 UTC, pond requested changes
PR is for a public repo but it includes a link to LNZL's private JIRA repository.

2023-07-26 20:16 UTC, ildomar-grings commented on CHANGELOG.md
> +- Critical vulnerabilities update [DS-2925](https://loyaltynz.atlassian.net/browse/DS-2925)
Good point. Reference removed.
Thanks

2023-07-26 21:05 UTC, merged